// exercises/react-advanced/react_todolist/src/TodoList.tsx
import React from "react";

import "./TodoList.css";
import Todo from "./Todo";
import TodoItem from "./TodoItem";

type Props = {
  todos: Array<Todo>;
  onToggle: (id: number) => void;
  onDelete: (id: number) => void;
};

const TodoList = (props: Props) => {
  return (
    <ul className="todolist">
      {props.todos.map((todo) => (
        <TodoItem
          key={todo.id}
          title={todo.title}
          completed={todo.completed}
          onToggle={() => props.onToggle(todo.id)}
          onDelete={() => props.onDelete(todo.id)}
        />
      ))}
    </ul>
  );
};

export default TodoList;

// exercises/vuejs/vue-3-todolist-typescript/solution/TodoList.vue
<template>
  <ul>
    <todo-item
      v-for="todo in todos"
      :key="todo.id"
      :title="todo.title"
      :completed="todo.completed"
      @toggle="$emit('toggle', todo.id)"
      @delete="$emit('delete', todo.id)"
    />
  </ul>
</template>

<script lang="ts">
import { PropType, defineComponent } from "vue";
import { Todo } from "./types";
import TodoItem from "./TodoItem.vue";

export default defineComponent({
  name: "TodoList",
  components: { TodoItem },
  props: {
    todos: {
      type: [] as PropType<Array<Todo>>,
      required: true,
    },
  },
});
</script>
