// exercises/vuejs/todolist-components/solution/TodoItem.vue
<template>
  <li @click="$emit('toggle')">
    <span
      :class="{todoitem: true, completed: completed}"
    >{{completed ? "DONE: " : "TODO: "}}{{ title }}</span>
    <button @click.stop="$emit('delete')">X</button>
  </li>
</template>

<script>
export default {
  props: ["title", "completed"]
};
</script>

<style scoped>
.completed {
  text-decoration: line-through;
}
</style>

// exercises/react-graphql/react_graphql_todo_client/src/TodoItem.js
import React, { memo } from "react";

function TodoItem({ title, completed, onToggle }) {
  return (
    <div
      className={completed ? "todo completed" : "todo"}
      onClick={() => onToggle()}
    >
      {completed ? "DONE" : "TODO"}: {title}
    </div>
  );
}

export default memo(TodoItem);
