// exercises/vuejs/todolist-simple/solution/App.vue
<template>
  <div id="app">
    <h1>Todo</h1>
    <form @submit.prevent="addTodo()">
      <input v-model="newTitle" />
      <button role="submit">add</button>
    </form>
    <ul>
      <li v-for="todo in todos" :key="todo.id" @click="todo.completed = !todo.completed">
        {{ todo.completed ? "DONE: " : "TODO: " }}{{ todo.title }}
        <button
          @click="deleteTodo(todo)"
        >X</button>
      </li>
    </ul>
    <section>
      <h1>stats</h1>
      completed: {{ completed }}, incomplete: {{ incomplete }}
    </section>
  </div>
</template>

<script>
export default {
  data: () => ({
    newTitle: "",
    todos: [
      { id: 1, title: "groceries", completed: false },
      { id: 2, title: "taxes", completed: true },
    ],
  }),
  methods: {
    addTodo() {
      this.todos.push({
        id: Math.max(0, ...this.todos.map((t) => t.id)) + 1,
        title: this.newTitle,
        completed: false,
      });
      this.newTitle = "";
    },
    deleteTodo(todo) {
      this.todos.splice(this.todos.indexOf(todo), 1);
    },
  },
  computed: {
    completed() {
      return this.todos.filter((t) => t.completed).length;
    },
    incomplete() {
      return this.todos.length - this.completed;
    },
  },
};
</script>

<style>
body {
  margin: 0;
}
</style>

<style scoped>
#app {
  height: 100vh;
  padding: 0px 8px;
  display: flex;
  flex-direction: column;
}
ul {
  overflow: auto;
}
</style>

// exercises/react-todolist-state-jsx-ts/src/App.tsx
import { useState } from "react";

import { Todo } from "./types";
import "./App.css";

export default function App() {
  const [todos, setTodos] = useState<Array<Todo>>([]);

  function addTodo(title: string) {
    let maxId = 0;
    for (let todo of todos) {
      maxId = Math.max(maxId, todo.id);
    }
    const newTodo = { id: maxId + 1, title: title, completed: false };
    setTodos([...todos, newTodo]);
  }

  function setTodoCompleted(id: number, completed: boolean) {
    setTodos(
      todos.map((todo) =>
        todo.id === id ? { ...todo, completed: completed } : todo
      )
    );
  }

  function deleteTodo(id: number) {
    setTodos(todos.filter((todo) => todo.id !== id));
  }

  const numTodos = todos.length;
  const numCompletedTodos = todos.filter((todo) => todo.completed).length;
  const numIncompleteTodos = numTodos - numCompletedTodos;

  const [newTitle, setNewTitle] = useState("");

  return (
    <div className="App">
      <h1>Todo</h1>
      <form
        onSubmit={(event) => {
          event.preventDefault();
          addTodo(newTitle);
          setNewTitle("");
        }}
      >
        <input
          value={newTitle}
          onChange={(event) => setNewTitle(event.target.value)}
        />
        <button type="submit">Add</button>
      </form>
      <ul className="TodoList">
        {todos.map((todo) => (
          <li
            key={todo.id}
            className={
              todo.completed
                ? "TodoItem TodoItem--Completed"
                : "TodoItem TodoItem--Incomplete"
            }
          >
            <input
              type="checkbox"
              checked={todo.completed}
              onChange={(event) =>
                setTodoCompleted(todo.id, event.target.checked)
              }
            />
            <span
              className={
                todo.completed
                  ? "TodoItem__Text TodoItem__Text--Completed"
                  : "TodoItem__Text"
              }
            >
              {todo.completed ? "DONE: " : "TODO: "}
              {todo.title}
            </span>
            <button onClick={() => deleteTodo(todo.id)}>delete</button>
          </li>
        ))}
      </ul>
      <div>
        {numTodos} todos ({numIncompleteTodos} incomplete, {numCompletedTodos}{" "}
        completed)
      </div>
    </div>
  );
}
