// exercises/vuejs/todolist-components/solution/Stats.vue
<template>
  <section>
    <h1>stats</h1>
    completed: {{completed}}, incomplete: {{incomplete}}
  </section>
</template>

<script>
export default {
  props: ["todos"],
  computed: {
    completed() {
      return this.todos.filter(t => t.completed).length;
    },
    incomplete() {
      return this.todos.length - this.completed;
    }
  }
};
</script>

// exercises/react-advanced/react_todolist/src/Stats.tsx
import React from "react";
import Todo from "./Todo";

type Props = {
  todos: Array<Todo>;
};

const Stats = (props: Props) => {
  const numIncomplete = props.todos.filter((todo) => !todo.completed).length;
  return (
    <div>
      {numIncomplete} open todos ({props.todos.length - numIncomplete}{" "}
      completed)
    </div>
  );
};

export default Stats;
