// exercises/react-graphql/react_graphql_todo_client/src/TodoList.js
import React, { memo } from "react";
import TodoItem from "./TodoItem";

function TodoList({ todos, onToggle }) {
  return (
    <div>
      {todos.map(todo => (
        <TodoItem
          key={todo.id}
          title={todo.title}
          completed={todo.completed}
          onToggle={() => onToggle(todo.id, !todo.completed)}
        />
      ))}
    </div>
  );
}

export default memo(TodoList);

// exercises/vuejs/todolist-components/solution/TodoList.vue
<template>
  <ul>
    <todo-item
      v-for="todo in todos"
      :key="todo.id"
      :title="todo.title"
      :completed="todo.completed"
      @toggle="$emit('toggle', todo.id)"
      @delete="$emit('delete', todo.id)"
    />
  </ul>
</template>

<script>
import TodoItem from "./TodoItem.vue";
export default {
  components: { TodoItem },
  props: ["todos"]
};
</script>
